/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export type TeleportGUIDStruct = {
  sourceDomain: PromiseOrValue<BytesLike>;
  targetDomain: PromiseOrValue<BytesLike>;
  receiver: PromiseOrValue<BytesLike>;
  operator: PromiseOrValue<BytesLike>;
  amount: PromiseOrValue<BigNumberish>;
  nonce: PromiseOrValue<BigNumberish>;
  timestamp: PromiseOrValue<BigNumberish>;
};

export type TeleportGUIDStructOutput = [
  string,
  string,
  string,
  string,
  BigNumber,
  BigNumber,
  number
] & {
  sourceDomain: string;
  targetDomain: string;
  receiver: string;
  operator: string;
  amount: BigNumber;
  nonce: BigNumber;
  timestamp: number;
};

export interface IL1TeleportGatewayInterface extends utils.Interface {
  functions: {
    "finalizeFlush(bytes32,uint256)": FunctionFragment;
    "finalizeRegisterTeleport((bytes32,bytes32,bytes32,bytes32,uint128,uint80,uint48))": FunctionFragment;
    "l1Escrow()": FunctionFragment;
    "l1TeleportRouter()": FunctionFragment;
    "l1Token()": FunctionFragment;
    "l2TeleportGateway()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "finalizeFlush"
      | "finalizeRegisterTeleport"
      | "l1Escrow"
      | "l1TeleportRouter"
      | "l1Token"
      | "l2TeleportGateway"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "finalizeFlush",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeRegisterTeleport",
    values: [TeleportGUIDStruct]
  ): string;
  encodeFunctionData(functionFragment: "l1Escrow", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "l1TeleportRouter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "l1Token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "l2TeleportGateway",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "finalizeFlush",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeRegisterTeleport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "l1Escrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "l1TeleportRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "l1Token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "l2TeleportGateway",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IL1TeleportGateway extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IL1TeleportGatewayInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    finalizeFlush(
      targetDomain: PromiseOrValue<BytesLike>,
      daiToFlush: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    finalizeRegisterTeleport(
      teleport: TeleportGUIDStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    l1Escrow(overrides?: CallOverrides): Promise<[string]>;

    l1TeleportRouter(overrides?: CallOverrides): Promise<[string]>;

    l1Token(overrides?: CallOverrides): Promise<[string]>;

    l2TeleportGateway(overrides?: CallOverrides): Promise<[string]>;
  };

  finalizeFlush(
    targetDomain: PromiseOrValue<BytesLike>,
    daiToFlush: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  finalizeRegisterTeleport(
    teleport: TeleportGUIDStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  l1Escrow(overrides?: CallOverrides): Promise<string>;

  l1TeleportRouter(overrides?: CallOverrides): Promise<string>;

  l1Token(overrides?: CallOverrides): Promise<string>;

  l2TeleportGateway(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    finalizeFlush(
      targetDomain: PromiseOrValue<BytesLike>,
      daiToFlush: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    finalizeRegisterTeleport(
      teleport: TeleportGUIDStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    l1Escrow(overrides?: CallOverrides): Promise<string>;

    l1TeleportRouter(overrides?: CallOverrides): Promise<string>;

    l1Token(overrides?: CallOverrides): Promise<string>;

    l2TeleportGateway(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    finalizeFlush(
      targetDomain: PromiseOrValue<BytesLike>,
      daiToFlush: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    finalizeRegisterTeleport(
      teleport: TeleportGUIDStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    l1Escrow(overrides?: CallOverrides): Promise<BigNumber>;

    l1TeleportRouter(overrides?: CallOverrides): Promise<BigNumber>;

    l1Token(overrides?: CallOverrides): Promise<BigNumber>;

    l2TeleportGateway(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    finalizeFlush(
      targetDomain: PromiseOrValue<BytesLike>,
      daiToFlush: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    finalizeRegisterTeleport(
      teleport: TeleportGUIDStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    l1Escrow(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    l1TeleportRouter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    l1Token(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    l2TeleportGateway(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
