/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IL1TeleportGateway } from "./IL1TeleportGateway";
export type { IL1TeleportRouter } from "./IL1TeleportRouter";
export type { IL2TeleportGateway } from "./IL2TeleportGateway";
