/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IL1TeleportGateway,
  IL1TeleportGatewayInterface,
} from "../../../common/TeleportInterfaces.sol/IL1TeleportGateway";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "targetDomain",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "daiToFlush",
        type: "uint256",
      },
    ],
    name: "finalizeFlush",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "sourceDomain",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "targetDomain",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "receiver",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "operator",
            type: "bytes32",
          },
          {
            internalType: "uint128",
            name: "amount",
            type: "uint128",
          },
          {
            internalType: "uint80",
            name: "nonce",
            type: "uint80",
          },
          {
            internalType: "uint48",
            name: "timestamp",
            type: "uint48",
          },
        ],
        internalType: "struct TeleportGUID",
        name: "teleport",
        type: "tuple",
      },
    ],
    name: "finalizeRegisterTeleport",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "l1Escrow",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "l1TeleportRouter",
    outputs: [
      {
        internalType: "contract IL1TeleportRouter",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "l1Token",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "l2TeleportGateway",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IL1TeleportGateway__factory {
  static readonly abi = _abi;
  static createInterface(): IL1TeleportGatewayInterface {
    return new utils.Interface(_abi) as IL1TeleportGatewayInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IL1TeleportGateway {
    return new Contract(address, _abi, signerOrProvider) as IL1TeleportGateway;
  }
}
