/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IL1TeleportGateway__factory } from "./IL1TeleportGateway__factory";
export { IL1TeleportRouter__factory } from "./IL1TeleportRouter__factory";
export { IL2TeleportGateway__factory } from "./IL2TeleportGateway__factory";
