/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as teleportInterfacesSol from "./TeleportInterfaces.sol";
export type { teleportInterfacesSol };
