/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface L1DaiGatewayInterface extends utils.Interface {
  functions: {
    "calculateL2TokenAddress(address)": FunctionFragment;
    "close()": FunctionFragment;
    "counterpartGateway()": FunctionFragment;
    "deny(address)": FunctionFragment;
    "finalizeInboundTransfer(address,address,address,uint256,bytes)": FunctionFragment;
    "getOutboundCalldata(address,address,address,uint256,bytes)": FunctionFragment;
    "inbox()": FunctionFragment;
    "isOpen()": FunctionFragment;
    "l1Dai()": FunctionFragment;
    "l1Escrow()": FunctionFragment;
    "l1Router()": FunctionFragment;
    "l2Counterpart()": FunctionFragment;
    "l2Dai()": FunctionFragment;
    "outboundTransfer(address,address,uint256,uint256,uint256,bytes)": FunctionFragment;
    "rely(address)": FunctionFragment;
    "wards(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "calculateL2TokenAddress"
      | "close"
      | "counterpartGateway"
      | "deny"
      | "finalizeInboundTransfer"
      | "getOutboundCalldata"
      | "inbox"
      | "isOpen"
      | "l1Dai"
      | "l1Escrow"
      | "l1Router"
      | "l2Counterpart"
      | "l2Dai"
      | "outboundTransfer"
      | "rely"
      | "wards"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "calculateL2TokenAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "close", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "counterpartGateway",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deny",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeInboundTransfer",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getOutboundCalldata",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(functionFragment: "inbox", values?: undefined): string;
  encodeFunctionData(functionFragment: "isOpen", values?: undefined): string;
  encodeFunctionData(functionFragment: "l1Dai", values?: undefined): string;
  encodeFunctionData(functionFragment: "l1Escrow", values?: undefined): string;
  encodeFunctionData(functionFragment: "l1Router", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "l2Counterpart",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "l2Dai", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "outboundTransfer",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "rely",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "wards",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateL2TokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "close", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "counterpartGateway",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deny", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeInboundTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOutboundCalldata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "inbox", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOpen", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "l1Dai", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "l1Escrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "l1Router", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "l2Counterpart",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "l2Dai", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "outboundTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rely", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wards", data: BytesLike): Result;

  events: {
    "Closed()": EventFragment;
    "Deny(address)": EventFragment;
    "DepositInitiated(address,address,address,uint256,uint256)": EventFragment;
    "Rely(address)": EventFragment;
    "TxToL2(address,address,uint256,bytes)": EventFragment;
    "WithdrawalFinalized(address,address,address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Closed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deny"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DepositInitiated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Rely"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TxToL2"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawalFinalized"): EventFragment;
}

export interface ClosedEventObject {}
export type ClosedEvent = TypedEvent<[], ClosedEventObject>;

export type ClosedEventFilter = TypedEventFilter<ClosedEvent>;

export interface DenyEventObject {
  usr: string;
}
export type DenyEvent = TypedEvent<[string], DenyEventObject>;

export type DenyEventFilter = TypedEventFilter<DenyEvent>;

export interface DepositInitiatedEventObject {
  l1Token: string;
  from: string;
  to: string;
  sequenceNumber: BigNumber;
  amount: BigNumber;
}
export type DepositInitiatedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  DepositInitiatedEventObject
>;

export type DepositInitiatedEventFilter =
  TypedEventFilter<DepositInitiatedEvent>;

export interface RelyEventObject {
  usr: string;
}
export type RelyEvent = TypedEvent<[string], RelyEventObject>;

export type RelyEventFilter = TypedEventFilter<RelyEvent>;

export interface TxToL2EventObject {
  from: string;
  to: string;
  seqNum: BigNumber;
  data: string;
}
export type TxToL2Event = TypedEvent<
  [string, string, BigNumber, string],
  TxToL2EventObject
>;

export type TxToL2EventFilter = TypedEventFilter<TxToL2Event>;

export interface WithdrawalFinalizedEventObject {
  l1Token: string;
  from: string;
  to: string;
  exitNum: BigNumber;
  amount: BigNumber;
}
export type WithdrawalFinalizedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  WithdrawalFinalizedEventObject
>;

export type WithdrawalFinalizedEventFilter =
  TypedEventFilter<WithdrawalFinalizedEvent>;

export interface L1DaiGateway extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: L1DaiGatewayInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    calculateL2TokenAddress(
      l1Token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    close(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    counterpartGateway(overrides?: CallOverrides): Promise<[string]>;

    deny(
      usr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    finalizeInboundTransfer(
      l1Token: PromiseOrValue<string>,
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getOutboundCalldata(
      l1Token: PromiseOrValue<string>,
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string] & { outboundCalldata: string }>;

    inbox(overrides?: CallOverrides): Promise<[string]>;

    isOpen(overrides?: CallOverrides): Promise<[BigNumber]>;

    l1Dai(overrides?: CallOverrides): Promise<[string]>;

    l1Escrow(overrides?: CallOverrides): Promise<[string]>;

    l1Router(overrides?: CallOverrides): Promise<[string]>;

    l2Counterpart(overrides?: CallOverrides): Promise<[string]>;

    l2Dai(overrides?: CallOverrides): Promise<[string]>;

    outboundTransfer(
      l1Token: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      maxGas: PromiseOrValue<BigNumberish>,
      gasPriceBid: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    rely(
      usr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    wards(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  calculateL2TokenAddress(
    l1Token: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  close(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  counterpartGateway(overrides?: CallOverrides): Promise<string>;

  deny(
    usr: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  finalizeInboundTransfer(
    l1Token: PromiseOrValue<string>,
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getOutboundCalldata(
    l1Token: PromiseOrValue<string>,
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  inbox(overrides?: CallOverrides): Promise<string>;

  isOpen(overrides?: CallOverrides): Promise<BigNumber>;

  l1Dai(overrides?: CallOverrides): Promise<string>;

  l1Escrow(overrides?: CallOverrides): Promise<string>;

  l1Router(overrides?: CallOverrides): Promise<string>;

  l2Counterpart(overrides?: CallOverrides): Promise<string>;

  l2Dai(overrides?: CallOverrides): Promise<string>;

  outboundTransfer(
    l1Token: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    maxGas: PromiseOrValue<BigNumberish>,
    gasPriceBid: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  rely(
    usr: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  wards(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    calculateL2TokenAddress(
      l1Token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    close(overrides?: CallOverrides): Promise<void>;

    counterpartGateway(overrides?: CallOverrides): Promise<string>;

    deny(usr: PromiseOrValue<string>, overrides?: CallOverrides): Promise<void>;

    finalizeInboundTransfer(
      l1Token: PromiseOrValue<string>,
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    getOutboundCalldata(
      l1Token: PromiseOrValue<string>,
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    inbox(overrides?: CallOverrides): Promise<string>;

    isOpen(overrides?: CallOverrides): Promise<BigNumber>;

    l1Dai(overrides?: CallOverrides): Promise<string>;

    l1Escrow(overrides?: CallOverrides): Promise<string>;

    l1Router(overrides?: CallOverrides): Promise<string>;

    l2Counterpart(overrides?: CallOverrides): Promise<string>;

    l2Dai(overrides?: CallOverrides): Promise<string>;

    outboundTransfer(
      l1Token: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      maxGas: PromiseOrValue<BigNumberish>,
      gasPriceBid: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    rely(usr: PromiseOrValue<string>, overrides?: CallOverrides): Promise<void>;

    wards(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "Closed()"(): ClosedEventFilter;
    Closed(): ClosedEventFilter;

    "Deny(address)"(usr?: PromiseOrValue<string> | null): DenyEventFilter;
    Deny(usr?: PromiseOrValue<string> | null): DenyEventFilter;

    "DepositInitiated(address,address,address,uint256,uint256)"(
      l1Token?: null,
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      sequenceNumber?: PromiseOrValue<BigNumberish> | null,
      amount?: null
    ): DepositInitiatedEventFilter;
    DepositInitiated(
      l1Token?: null,
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      sequenceNumber?: PromiseOrValue<BigNumberish> | null,
      amount?: null
    ): DepositInitiatedEventFilter;

    "Rely(address)"(usr?: PromiseOrValue<string> | null): RelyEventFilter;
    Rely(usr?: PromiseOrValue<string> | null): RelyEventFilter;

    "TxToL2(address,address,uint256,bytes)"(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      seqNum?: PromiseOrValue<BigNumberish> | null,
      data?: null
    ): TxToL2EventFilter;
    TxToL2(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      seqNum?: PromiseOrValue<BigNumberish> | null,
      data?: null
    ): TxToL2EventFilter;

    "WithdrawalFinalized(address,address,address,uint256,uint256)"(
      l1Token?: null,
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      exitNum?: PromiseOrValue<BigNumberish> | null,
      amount?: null
    ): WithdrawalFinalizedEventFilter;
    WithdrawalFinalized(
      l1Token?: null,
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      exitNum?: PromiseOrValue<BigNumberish> | null,
      amount?: null
    ): WithdrawalFinalizedEventFilter;
  };

  estimateGas: {
    calculateL2TokenAddress(
      l1Token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    close(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    counterpartGateway(overrides?: CallOverrides): Promise<BigNumber>;

    deny(
      usr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    finalizeInboundTransfer(
      l1Token: PromiseOrValue<string>,
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getOutboundCalldata(
      l1Token: PromiseOrValue<string>,
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    inbox(overrides?: CallOverrides): Promise<BigNumber>;

    isOpen(overrides?: CallOverrides): Promise<BigNumber>;

    l1Dai(overrides?: CallOverrides): Promise<BigNumber>;

    l1Escrow(overrides?: CallOverrides): Promise<BigNumber>;

    l1Router(overrides?: CallOverrides): Promise<BigNumber>;

    l2Counterpart(overrides?: CallOverrides): Promise<BigNumber>;

    l2Dai(overrides?: CallOverrides): Promise<BigNumber>;

    outboundTransfer(
      l1Token: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      maxGas: PromiseOrValue<BigNumberish>,
      gasPriceBid: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    rely(
      usr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    wards(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    calculateL2TokenAddress(
      l1Token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    close(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    counterpartGateway(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deny(
      usr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    finalizeInboundTransfer(
      l1Token: PromiseOrValue<string>,
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getOutboundCalldata(
      l1Token: PromiseOrValue<string>,
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    inbox(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isOpen(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    l1Dai(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    l1Escrow(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    l1Router(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    l2Counterpart(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    l2Dai(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    outboundTransfer(
      l1Token: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      maxGas: PromiseOrValue<BigNumberish>,
      gasPriceBid: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    rely(
      usr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    wards(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
