/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as daiEchidnaTestSol from "./DaiEchidnaTest.sol";
export type { daiEchidnaTestSol };
import type * as testBridgeUpgradeSpellSol from "./TestBridgeUpgradeSpell.sol";
export type { testBridgeUpgradeSpellSol };
import type * as testDaiMintSpellSol from "./TestDaiMintSpell.sol";
export type { testDaiMintSpellSol };
export type { BadSpell } from "./BadSpell";
