[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['dss-test/=lib/dss-test/src/']
fs_permissions = [{ access = "read-write", path = "./"}]

# See more config options https://github.com/gakonst/foundry/tree/master/config
