/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  L2CrossDomainEnabled,
  L2CrossDomainEnabledInterface,
} from "../../l2/L2CrossDomainEnabled";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "TxToL1",
    type: "event",
  },
];

export class L2CrossDomainEnabled__factory {
  static readonly abi = _abi;
  static createInterface(): L2CrossDomainEnabledInterface {
    return new utils.Interface(_abi) as L2CrossDomainEnabledInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): L2CrossDomainEnabled {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as L2CrossDomainEnabled;
  }
}
