/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  MintLike,
  MintLikeInterface,
} from "../../../test/TestDaiMintSpell.sol/MintLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class MintLike__factory {
  static readonly abi = _abi;
  static createInterface(): MintLikeInterface {
    return new utils.Interface(_abi) as MintLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MintLike {
    return new Contract(address, _abi, signerOrProvider) as MintLike;
  }
}
