/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { BridgeLike, BridgeLikeInterface } from "../BridgeLike";

const _abi = [
  {
    inputs: [],
    name: "close",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "l2Dai",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class BridgeLike__factory {
  static readonly abi = _abi;
  static createInterface(): BridgeLikeInterface {
    return new utils.Interface(_abi) as BridgeLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BridgeLike {
    return new Contract(address, _abi, signerOrProvider) as BridgeLike;
  }
}
