/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Mintable, MintableInterface } from "../Mintable";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "usr",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "wad",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "usr",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "wad",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Mintable__factory {
  static readonly abi = _abi;
  static createInterface(): MintableInterface {
    return new utils.Interface(_abi) as MintableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Mintable {
    return new Contract(address, _abi, signerOrProvider) as Mintable;
  }
}
