/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  AuthLike,
  AuthLikeInterface,
} from "../../../test/TestBridgeUpgradeSpell.sol/AuthLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "usr",
        type: "address",
      },
    ],
    name: "deny",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "usr",
        type: "address",
      },
    ],
    name: "rely",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class AuthLike__factory {
  static readonly abi = _abi;
  static createInterface(): AuthLikeInterface {
    return new utils.Interface(_abi) as AuthLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AuthLike {
    return new Contract(address, _abi, signerOrProvider) as AuthLike;
  }
}
