/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as daiEchidnaTestSol from "./DaiEchidnaTest.sol";
export * as testBridgeUpgradeSpellSol from "./TestBridgeUpgradeSpell.sol";
export * as testDaiMintSpellSol from "./TestDaiMintSpell.sol";
export { BadSpell__factory } from "./BadSpell__factory";
