/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface L1CrossDomainEnabledInterface extends utils.Interface {
  functions: {
    "inbox()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "inbox"): FunctionFragment;

  encodeFunctionData(functionFragment: "inbox", values?: undefined): string;

  decodeFunctionResult(functionFragment: "inbox", data: BytesLike): Result;

  events: {
    "TxToL2(address,address,uint256,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "TxToL2"): EventFragment;
}

export interface TxToL2EventObject {
  from: string;
  to: string;
  seqNum: BigNumber;
  data: string;
}
export type TxToL2Event = TypedEvent<
  [string, string, BigNumber, string],
  TxToL2EventObject
>;

export type TxToL2EventFilter = TypedEventFilter<TxToL2Event>;

export interface L1CrossDomainEnabled extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: L1CrossDomainEnabledInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    inbox(overrides?: CallOverrides): Promise<[string]>;
  };

  inbox(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    inbox(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "TxToL2(address,address,uint256,bytes)"(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      seqNum?: PromiseOrValue<BigNumberish> | null,
      data?: null
    ): TxToL2EventFilter;
    TxToL2(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      seqNum?: PromiseOrValue<BigNumberish> | null,
      data?: null
    ): TxToL2EventFilter;
  };

  estimateGas: {
    inbox(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    inbox(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
