/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Alice__factory } from "./Alice__factory";
export { DaiEchidnaTest__factory } from "./DaiEchidnaTest__factory";
