/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as l2DaiGatewaySol from "./L2DaiGateway.sol";
export type { l2DaiGatewaySol };
import type * as l2DaiTeleportGatewaySol from "./L2DaiTeleportGateway.sol";
export type { l2DaiTeleportGatewaySol };
import type * as daiSol from "./dai.sol";
export type { daiSol };
export type { L2CrossDomainEnabled } from "./L2CrossDomainEnabled";
export type { L2GovernanceRelay } from "./L2GovernanceRelay";
export type { L2ITokenGateway } from "./L2ITokenGateway";
