/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { BaseContract, BigNumber, BigNumberish, Signer, utils } from "ethers";
import { EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface L2CrossDomainEnabledInterface extends utils.Interface {
  functions: {};

  events: {
    "TxToL1(address,address,uint256,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "TxToL1"): EventFragment;
}

export type TxToL1Event = TypedEvent<
  [string, string, BigNumber, string],
  { from: string; to: string; id: BigNumber; data: string }
>;

export type TxToL1EventFilter = TypedEventFilter<TxToL1Event>;

export interface L2CrossDomainEnabled extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: L2CrossDomainEnabledInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "TxToL1(address,address,uint256,bytes)"(
      from?: string | null,
      to?: string | null,
      id?: BigNumberish | null,
      data?: null
    ): TxToL1EventFilter;
    TxToL1(
      from?: string | null,
      to?: string | null,
      id?: BigNumberish | null,
      data?: null
    ): TxToL1EventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
