/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface L2GovernanceRelayInterface extends utils.Interface {
  functions: {
    "l1GovernanceRelay()": FunctionFragment;
    "relay(address,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "l1GovernanceRelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "relay",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "l1GovernanceRelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "relay", data: BytesLike): Result;

  events: {
    "TxToL1(address,address,uint256,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "TxToL1"): EventFragment;
}

export type TxToL1Event = TypedEvent<
  [string, string, BigNumber, string],
  { from: string; to: string; id: BigNumber; data: string }
>;

export type TxToL1EventFilter = TypedEventFilter<TxToL1Event>;

export interface L2GovernanceRelay extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: L2GovernanceRelayInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    l1GovernanceRelay(overrides?: CallOverrides): Promise<[string]>;

    relay(
      target: string,
      targetData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  l1GovernanceRelay(overrides?: CallOverrides): Promise<string>;

  relay(
    target: string,
    targetData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    l1GovernanceRelay(overrides?: CallOverrides): Promise<string>;

    relay(
      target: string,
      targetData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "TxToL1(address,address,uint256,bytes)"(
      from?: string | null,
      to?: string | null,
      id?: BigNumberish | null,
      data?: null
    ): TxToL1EventFilter;
    TxToL1(
      from?: string | null,
      to?: string | null,
      id?: BigNumberish | null,
      data?: null
    ): TxToL1EventFilter;
  };

  estimateGas: {
    l1GovernanceRelay(overrides?: CallOverrides): Promise<BigNumber>;

    relay(
      target: string,
      targetData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    l1GovernanceRelay(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    relay(
      target: string,
      targetData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
