/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  TokenLike,
  TokenLikeInterface,
} from "../../../l1/L1DaiGateway.sol/TokenLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_from",
        type: "address",
      },
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_value",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [
      {
        internalType: "bool",
        name: "success",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class TokenLike__factory {
  static readonly abi = _abi;
  static createInterface(): TokenLikeInterface {
    return new utils.Interface(_abi) as TokenLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TokenLike {
    return new Contract(address, _abi, signerOrProvider) as TokenLike;
  }
}
