version: '3.9'
services:
  web:
    build: .
    # command: 'sh'
    # stdin_open: true
    # tty: true
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    env_file: .env
  postgres:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
