name: Fuzz

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  echidna-optimism-dai-bridge:
    name: Echidna for optimism-dai-bridge
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/optimism-dai-bridge
    strategy:
      fail-fast: false
      matrix:
        testName:
          - DaiEchidnaTest
    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache YARN dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Install node dependencies
        run: yarn install --frozen-lockfile

      - name: Install pip3
        run: |
          python -m pip install --upgrade pip
      - name: Install slither
        run: |
          pip3 install slither-analyzer
      - name: Install solc-select
        run: |
          pip3 install solc-select
      - name: Set solc v0.7.6
        run: |
          solc-select install 0.7.6
          solc-select use 0.7.6
      - name: Install echidna
        run: |
          sudo wget -O /tmp/echidna-test.tar.gz https://github.com/crytic/echidna/releases/download/v1.7.2/echidna-test-1.7.2-Ubuntu-18.04.tar.gz
          sudo tar -xf /tmp/echidna-test.tar.gz -C /usr/bin
          sudo chmod +x /usr/bin/echidna-test
      - name: Run ${{ matrix.testName }}
        run: echidna-test . --contract ${{ matrix.testName }} --config echidna.config.ci.yml

  echidna-arbitrum-dai-bridge:
    name: Echidna for arbitrum-dai-bridge
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/arbitrum-dai-bridge
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache YARN dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Install node dependencies
        run: yarn install --frozen-lockfile

      - name: Install pip3
        run: |
          python -m pip install --upgrade pip
      - name: Install slither
        run: |
          pip3 install slither-analyzer
      - name: Install solc-select
        run: |
          pip3 install solc-select
      - name: Set solc v0.6.11
        run: |
          solc-select install 0.6.11
          solc-select use 0.6.11
      - name: Install echidna
        run: |
          sudo wget -O /tmp/echidna-test.tar.gz https://github.com/crytic/echidna/releases/download/v1.7.2/echidna-test-1.7.2-Ubuntu-18.04.tar.gz
          sudo tar -xf /tmp/echidna-test.tar.gz -C /usr/bin
          sudo chmod +x /usr/bin/echidna-test
      - name: Run DaiEchidnaTest
        run: echidna-test . --contract DaiEchidnaTest --config echidna.config.ci.yml
