name: Goerli Teleport Flush Keeper

on:
  push:
    branches:
      - master
    paths:
      - packages/teleport-keeper/**
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  goerli-teleport-keeper:
    name: Goerli Teleport Keeper
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/teleport-keeper

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Build keeper container
        run: docker build -t teleport-keeper .
      - name: Run keeper container
        run: docker run -t teleport-keeper ${{ secrets.GOERLI_RPC_URL }} ${{ secrets.TEST_KEEPER_PRIV_KEY }}
