name: Testnet Teleport Flush Keepers

on:
  push:
    branches:
      - master
    paths:
      - packages/teleport-keeper/**
  pull_request:

jobs:
  arbitrum-rinkeby-teleport-keeper:
    name: Arbitrum Rinkeby Teleport Keeper
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/teleport-keeper

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Build keeper container
        run: docker build -t teleport-keeper .
      - name: Run keeper container
        run: docker run -t teleport-keeper ${{ secrets.RINKEBY_RPC_URL }} ${{ secrets.TEST_KEEPER_PRIV_KEY }}

  optimism-kovan-teleport-keeper:
    name: Optimism Kovan Teleport Keeper
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/teleport-keeper
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Build keeper container
        run: docker build -t teleport-keeper .
      - name: Run keeper container
        run: docker run -t teleport-keeper ${{ secrets.KOVAN_RPC_URL }} ${{ secrets.TEST_KEEPER_PRIV_KEY }}
