name: Teleport Optimism integration tests

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  teleport-opt-int-tests:
    name: Tests
    defaults:
      run:
        working-directory: ./packages/teleport-integration-tests
    strategy:
      matrix:
        node: ["14"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v1-node
        with:
          node-version: ${{ matrix.node }}

      - name: Install nix 2.3.6
        uses: cachix/install-nix-action@v13
        with:
          install_url: https://releases.nixos.org/nix/nix-2.3.6/install
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Use maker and dapp cachix
        uses: cachix/cachix-action@v10
        with:
          name: maker
          extraPullNames: dapp

      - name: Create env file
        run: |
          touch .env
          echo RINKEBY_RPC_URL="${{ secrets.RINKEBY_RPC_URL }}" >> .env
          echo KOVAN_RPC_URL="${{ secrets.KOVAN_RPC_URL }}" >> .env
          echo TEST_OPTIMISM_L1_RPC_URL="http://127.0.0.1:9545" >> .env
          echo TEST_OPTIMISM_L2_RPC_URL="http://127.0.0.1:8545" >> .env
          echo DEPLOYER_PRIV_KEY="${{ secrets.INTEGRATION_TEST_DEPLOYER_PRIV_KEY }}" >> .env
          echo USER_PRIV_KEY="${{ secrets.TEST_USER_PRIV_KEY }}" >> .env

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.OS }}-${{ matrix.node }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.OS }}-${{ matrix.node }}-yarn-cache-
      - run: yarn
      - run: ./scripts/setup.sh

      - run: yarn lint
      - run: yarn format
      - run: yarn build

      - run: ./scripts/build-infra.sh
      - run: ./scripts/run-infra.sh&
      - run: yarn ts-node ./scripts/ensure-infra-up.ts
      - run: sleep 60 # give it some time to initialize

      - run: yarn test:optimism
