name: Submodule update

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  submodule_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.PAT }}

      - name: Git Submodule Update
        run: |
          ./scripts/bump-deps.sh

      - uses: peter-evans/create-pull-request@v3
        with:
          base: master
          branch: bump-submodules
          title: Bump submodules
          body: Automated PR created after out of date submodules were detected
          reviewers: krzkaczor
          token: ${{ secrets.PAT }}
